config/routes.rb
ExampleSqliteChartjs::Application.routes.draw do
  root to: 'examples#index'

  get '/line', to: 'examples#line'
  get '/bar', to: 'examples#bar'
  get '/radar', to: 'examples#radar'
  get '/polar_area', to: 'examples#polar_area'
  get '/pie', to: 'examples#pie'
  get '/doughnut', to: 'examples#doughnut'
end

app/models/dataset.rb
class Dataset < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  before_filter :fetch_datasets, except: [:index]

  def index
    @title = 'Overview of examples'
    @datasets = Dataset.all
    respond_to do |format|
      format.html
      format.xml { render xml: @datasets.to_xml }
      format.json { render json: @datasets }
    end
  end

  def line
    @title = 'Line Demo'
    respond_to do |format|
      format.html
      format.xml { render xml: @datasets.to_xml }
      format.json { render json: @datasets }
    end
  end

  def bar
    @title = 'Bar Demo'
    respond_to do |format|
      format.html
      format.xml { render xml: @datasets.to_xml }
      format.json { render json: @datasets }
    end
  end

  def radar
    @title = 'Radar Demo'
    respond_to do |format|
      format.html
      format.xml { render xml: @datasets.to_xml }
      format.json { render json: @datasets }
    end
  end

  def polar_area
    @title = 'Polar Area Demo'
    respond_to do |format|
      format.html
      format.xml { render xml: @datasets.to_xml }
      format.json { render json: @datasets }
    end
  end

  def pie
   @title = 'Pie Demo'
   respond_to do |format|
      format.html
      format.xml { render xml: @datasets.to_xml }
      format.json { render json: @datasets }
    end
  end

  def doughnut
    @title = 'Doughnut Demo'
    respond_to do |format|
      format.html
      format.xml { render xml: @datasets.to_xml }
      format.json { render json: @datasets }
    end
  end

  private
    def fetch_datasets
      count = params[:count] ? params[:count] : 5
      @datasets = Dataset.limit(count) # FIXME: Not the safties way to parse the params into the query (SQLInjection Alert)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/views/chart_templates/_bar_chart.js.erb
<script>
  var data = {
    labels : ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
    datasets : [
      <% datasets.each_with_index do |dataset, index| %>
        {
          fillColor : 'rgba(<%= rand(0..255) %>, <%= rand(0..255) %>, <%= rand(0..255) %>, <%= rand(0.1..1.0) %>)',
          strokeColor : 'rgba(<%= rand(0..255) %>, <%= rand(0..255) %>, <%= rand(0..255) %>, <%= rand(0.1..1.0) %>)',
          pointColor : 'rgba(<%= rand(0..255) %>, <%= rand(0..255) %>, <%= rand(0..255) %>, <%= rand(0.1..1.0) %>)',
          pointStrokeColor : '#FFFFFF',
          data : [
            <%= dataset.one %>,
            <%= dataset.two %>,
            <%= dataset.three %>,
            <%= dataset.four %>,
            <%= dataset.five %>,
            <%= dataset.six %>,
            <%= dataset.seven %>,
            <%= dataset.eight %>,
            <%= dataset.nine %>,
            <%= dataset.ten %>
          ]
        }
        <%= index < datasets.size-1 ? ', ' : '' %>
      <% end %>
    ]
  }

  barChart = new Chart($('#canvas').get(0).getContext('2d')).Bar(data)
</script>

app/views/chart_templates/_doughnut_chart.js.erb
<script>
  var data = [
    <% datasets.each_with_index do |dataset, index| %>
      {
        value: <%= dataset.one %>,
        color: '#<%= '%06x' % (rand * 0xffffff) %>'
      }
      <%= index < datasets.size-1 ? ', ' : '' %>
    <% end %>
  ]

  doughnutChart = new Chart($('#canvas').get(0).getContext('2d')).Doughnut(data)
</script>

app/views/chart_templates/_line_chart.js.erb
<script>
  var data = {
    labels : ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
    datasets : [
      <% datasets.each_with_index do |dataset, index| %>
        {
          fillColor : 'rgba(<%= rand(0..255) %>, <%= rand(0..255) %>, <%= rand(0..255) %>, <%= rand(0.1..1.0) %>)',
          strokeColor : 'rgba(<%= rand(0..255) %>, <%= rand(0..255) %>, <%= rand(0..255) %>, <%= rand(0.1..1.0) %>)',
          pointColor : 'rgba(<%= rand(0..255) %>, <%= rand(0..255) %>, <%= rand(0..255) %>, <%= rand(0.1..1.0) %>)',
          pointStrokeColor : '#FFFFFF',
          data : [
            <%= dataset.one %>,
            <%= dataset.two %>,
            <%= dataset.three %>,
            <%= dataset.four %>,
            <%= dataset.five %>,
            <%= dataset.six %>,
            <%= dataset.seven %>,
            <%= dataset.eight %>,
            <%= dataset.nine %>,
            <%= dataset.ten %>
          ]
        }
        <%= index < datasets.size-1 ? ', ' : '' %>
      <% end %>
    ]
  }

  lineChart = new Chart($('#canvas').get(0).getContext('2d')).Line(data)
</script>

app/views/chart_templates/_pie_chart.js.erb
<script>
  var data = [
    <% datasets.each_with_index do |dataset, index| %>
      {
        value: <%= dataset.one %>,
        color: '#<%= '%06x' % (rand * 0xffffff) %>'
      }
      <%= index < datasets.size-1 ? ', ' : '' %>
    <% end %>
  ]

  pieChart = new Chart($('#canvas').get(0).getContext('2d')).Pie(data)
</script>

app/views/chart_templates/_polar_area_chart.js.erb
<script>
  var data = [
    <% datasets.each_with_index do |dataset, index| %>
      {
        value: <%= dataset.one %>,
        color: '#<%= '%06x' % (rand * 0xffffff) %>'
      }
      <%= index < datasets.size-1 ? ', ' : '' %>
    <% end %>
  ]

  polarAreaChart = new Chart($('#canvas').get(0).getContext('2d')).PolarArea(data)
</script>

app/views/chart_templates/_radar_chart.js.erb
<script>
  var data = {
    labels : ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
    datasets : [
      <% datasets.each_with_index do |dataset, index| %>
        {
          fillColor : 'rgba(<%= rand(0..255) %>, <%= rand(0..255) %>, <%= rand(0..255) %>, <%= rand(0.1..1.0) %>)',
          strokeColor : 'rgba(<%= rand(0..255) %>, <%= rand(0..255) %>, <%= rand(0..255) %>, <%= rand(0.1..1.0) %>)',
          pointColor : 'rgba(<%= rand(0..255) %>, <%= rand(0..255) %>, <%= rand(0..255) %>, <%= rand(0.1..1.0) %>)',
          pointStrokeColor : '#FFFFFF',
          data : [
            <%= dataset.one %>,
            <%= dataset.two %>,
            <%= dataset.three %>,
            <%= dataset.four %>,
            <%= dataset.five %>,
            <%= dataset.six %>,
            <%= dataset.seven %>,
            <%= dataset.eight %>,
            <%= dataset.nine %>,
            <%= dataset.ten %>
          ]
        }
        <%= index < datasets.size-1 ? ', ' : '' %>
      <% end %>
    ]
  }

  radarChart = new Chart($('#canvas').get(0).getContext('2d')).Radar(data)
</script>

app/views/examples/bar.haml
.span12
  %ul.breadcrumb
    %li
      = link_to 'Overview', root_path
      %span.divider
        \/
    %li.active
      Bar Demo
.span12
  = render 'shared/rows_fetched_well', rows_fetched: @datasets.count
- if params[:no_chart] != 1.to_s
  .span12
    = render 'shared/chart_canvas', datasets: @datasets
  = render 'chart_templates/bar_chart.js.erb', datasets: @datasets
- if params[:no_table] != 1.to_s
  .span12
    = render 'shared/dataset_table'

app/views/examples/doughnut.haml
.span12
  %ul.breadcrumb
    %li
      = link_to 'Overview', root_path
      %span.divider
        \/
    %li.active
      Dougnut Demo
.span12
  = render 'shared/rows_fetched_well', rows_fetched: @datasets.count
- if params[:no_chart] != 1.to_s
  .span12
    = render 'shared/chart_canvas', datasets: @datasets
  = render 'chart_templates/doughnut_chart.js.erb', datasets: @datasets
- if params[:no_table] != 1.to_s
  .span12
    = render 'shared/dataset_table'

app/views/examples/index.haml
.span12
  %ul.breadcrumb
    %li.active
      Overview
.span6.offset3
  %table.table.table-bordered.table-striped.tablesorter
    %thead
      %tr
        %th(colspan='3')
          Chart examples
    %tbody
      %tr
        %td
          = link_to 'Line', line_path
        %td
          = link_to 'Line (no Chart)', line_path(no_chart: 1)
        %td
          = link_to 'Line (no Table)', line_path(no_table: 1)
      %tr
        %td
          = link_to 'Bar', bar_path
        %td
          = link_to 'Bar (no Chart)', bar_path(no_chart: 1)
        %td
          = link_to 'Bar (no Table)', bar_path(no_table: 1)
      %tr
        %td
          = link_to 'Radar', radar_path
        %td
          = link_to 'Radar (no Chart)', radar_path(no_chart: 1)
        %td
          = link_to 'Radar (no Table)', radar_path(no_table: 1)
      %tr
        %td
          = link_to 'Polar area', polar_area_path
        %td
          = link_to 'Polar area (no Chart)', polar_area_path(no_chart: 1)
        %td
          = link_to 'Polar area (no Table)', polar_area_path(no_table: 1)
      %tr
        %td
          = link_to 'Pie', pie_path
        %td
          = link_to 'Pie (no Chart)', pie_path(no_chart: 1)
        %td
          = link_to 'Pie (no Table)', pie_path(no_table: 1)
      %tr
        %td
          = link_to 'Doughnut', doughnut_path
        %td
          = link_to 'Doughnut (no Chart)', doughnut_path(no_chart: 1)
        %td
          = link_to 'Doughnut (no Table)', doughnut_path(no_table: 1)
.span6.offset3
  .well
    There is a total of
    %br
    %strong
      = @datasets.count
    %br
    row(s) in the database
.span6.offset3
  .well
    %strong
      Available GET-Parameters:
    %br
    ?count=X
    %br
    ?no_chart=X
    %br
    ?no_table=X
.span6.offset3
  .well
    %strong
      Available APIs:
    %br
    There are XML and JSON APIs available. Just append .json or .xml to the url
    %br
    = link_to 'localhost:3000/pie.json', pie_path(format: :json)
    %br
    = link_to 'localhost:3000/doughnut.xml', doughnut_path(format: :xml)

app/views/examples/line.haml
.span12
  %ul.breadcrumb
    %li
      = link_to 'Overview', root_path
      %span.divider
        \/
    %li.active
      Line Demo
.span12
  = render 'shared/rows_fetched_well', rows_fetched: @datasets.count
- if params[:no_chart] != 1.to_s
  .span12
    = render 'shared/chart_canvas', datasets: @datasets
  = render 'chart_templates/line_chart.js.erb', datasets: @datasets
- if params[:no_table] != 1.to_s
  .span12
    = render 'shared/dataset_table'

app/views/examples/pie.haml
.span12
  %ul.breadcrumb
    %li
      = link_to 'Overview', root_path
      %span.divider
        \/
    %li.active
      Pie Demo
.span12
  = render 'shared/rows_fetched_well', rows_fetched: @datasets.count
- if params[:no_chart] != 1.to_s
  .span12
    = render 'shared/chart_canvas', datasets: @datasets
  = render 'chart_templates/pie_chart.js.erb', datasets: @datasets
- if params[:no_table] != 1.to_s
  .span12
    = render 'shared/dataset_table'

app/views/examples/polar_area.haml
.span12
  %ul.breadcrumb
    %li
      = link_to 'Overview', root_path
      %span.divider
        \/
    %li.active
      Polar Area Demo
.span12
  = render 'shared/rows_fetched_well', rows_fetched: @datasets.count
- if params[:no_chart] != 1.to_s
  .span12
    = render 'shared/chart_canvas', datasets: @datasets
  = render 'chart_templates/polar_area_chart.js.erb', datasets: @datasets
- if params[:no_table] != 1.to_s
  .span12
    = render 'shared/dataset_table'

app/views/examples/radar.haml
.span12
  %ul.breadcrumb
    %li
      = link_to 'Overview', root_path
      %span.divider
        \/
    %li.active
      Radar Demo
.span12
  = render 'shared/rows_fetched_well', rows_fetched: @datasets.count
- if params[:no_chart] != 1.to_s
  .span12
    = render 'shared/chart_canvas', datasets: @datasets
  = render 'chart_templates/radar_chart.js.erb', datasets: @datasets
- if params[:no_table] != 1.to_s
  .span12
    = render 'shared/dataset_table'

app/views/layouts/_navigation.haml
.navbar.navbar-inverse.navbar-fixed-top
  .navbar-inner
    .container
      = link_to 'SQLite Chart.js Example (mobile ready)', root_path, class: 'brand'

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{charset: 'utf-8'}
    %meta{'http-equiv' => 'Content-Type', content: 'text/html; charset=utf-8'}
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0, user-scalable=0'}
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %title
      = @title ? "#{@title} - Example SQLite Chart.js" : 'Example SQLite Chart.js'
  %body
    = render 'layouts/navigation'
    .container
      .row
        = yield

app/views/shared/_chart_canvas.haml
- if datasets.any?
  .chart
    %canvas#canvas{height: '450', width: '1170'}

app/views/shared/_dataset_table.haml
- if @datasets.any?
  %table.table.table-bordered.table-striped.tablesorter
    %thead
      %tr
        %th.hidden-phone.hidden-tablet
          No.
        %th
          1
        %th
          2
        %th
          3
        %th
          4
        %th
          5
        %th
          6
        %th
          7
        %th
          8
        %th
          9
        %th
          10
    %tbody
      - @datasets.each_with_index do |dataset, index|
        %tr
          %td.hidden-phone.hidden-tablet
            = "##{index+1}"
          %td
            = dataset.one
          %td
            = dataset.two
          %td
            = dataset.three
          %td
            = dataset.four
          %td
            = dataset.five
          %td
            = dataset.six
          %td
            = dataset.seven
          %td
            = dataset.eight
          %td
            = dataset.nine
          %td
            = dataset.ten
- else
  .alert.alert-error
    %strong
      There is no data available to display

app/views/shared/_rows_fetched_well.haml
.well
  %strong
    = "#{rows_fetched} row(s) fetched from the database"
  %br
    Can be changed with a GET-Parameter (e.g. localhost:3000?count=20)